// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw4VH1QZrE2XI8ZswTBZQgiXfvXio0-Zo',
    appId: '1:1087904092637:web:d8b8fadd93786d94696634',
    messagingSenderId: '1087904092637',
    projectId: 'co-caro-b645d',
    authDomain: 'co-caro-b645d.firebaseapp.com',
    storageBucket: 'co-caro-b645d.firebasestorage.app',
    measurementId: 'G-1FLCRZJT51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZurCSGokTwbDD_6lcW0wjceqdFs7spkc',
    appId: '1:1087904092637:android:456aa9fe9e03c81a696634',
    messagingSenderId: '1087904092637',
    projectId: 'co-caro-b645d',
    storageBucket: 'co-caro-b645d.firebasestorage.app',
  );
}
